package com.comp2042;

/**
 * Represents the source of an event in the application
 * <p>
 * The {@code EventSource} enum distinguishes whether an event was triggered directly by the user or by a background thread
 */
public enum EventSource {
    /**
     * Indicates the event originated from direct user interaction (e.g., keyboard input, mouse click)
     */
    USER, 
    
    /**
     * Indicates the event was generated by a background thread or automated process (e.g., timers, game loop)
     */
    THREAD
}
